
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: snapshot_timetamp_check
      description: "checking even values in the column"
      columns:
          - name: score
            description: "shipping score for this table"
            tests:
                - non_numeric_test
                - warn_if_odd